### ISSUE TITLE
eval llama-7b from huggingface

### ISSUE THREAD

**Issue by QeeKhan** [jayelm/gisting#11]
I used llama-7b [hf](https://huggingface.co/huggyllama/llama-7b) from huggingface to evaluate on 3090，and it come out a lot of nonsense，like below。I test flan-t5 and everything is ok。 

roup toggletags...]NAMEGroup toggletags...]NAMEGroup toggletags...]NAMEGroup toggletags...]NAMEGroup toggletags...]NAMEGroup toggletags...]NAMEGroup toggletags...]NAMEGroup toggletags...]NAMEGroup toggletags...]NAMEGroup toggletags...]NAMEGroup togglePY AustralMo prince ’ impedGroup togglePY AustralMo prince ’ impedGroup togglePY AustralMo prince ’ impedGroup togglePY AustralMo prince ’ impedGroup togglePY AustralMo prince ’ impedGroup togglePY AustralMo prince ’ impedGroup togglePY AustralMo prince ’ impedGroup togglePY AustralMo prince ’ impedGroup togglePY AustralMo prince ’ impedGroup togglePY AustralMo prince ’ impedGroup togglePY AustralMo prince ’ impedGroup togglePY AustralMo prince ’ impedGroup togglePY Austral Upon (/##################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################

**Comment by jayelm** [comment]
Hi, please see issue #7.

**Comment by jayelm** [comment]
I'm going to close this issue for now, but please let me know if you continue to have issues!
