### ISSUE TITLE
Conceptual Clarification

### ISSUE THREAD

**Issue by FFFiend** [jayelm/gisting#13]
Hey there, I was wondering whether the purpose of this at a high level (prompt compression) is to be able to save on compute when given a prompt (or part of a prompt) that the model has already seen (kinda like Dynamic Programming?) Or is it to be able to feed larger than possible (larger than LLama-7B/Flan-T5's context lengths) prompts into the model?

I tried testing on a string of char length 16001 and ran out of memory on a 40GB A100,  so I was just wondering whether I'm using this for the wrong purpose. 

Cheers.

**Comment by jayelm** [comment]
Hi,

It's mostly saving on compute with prompts the model has already been seen. Extending context-length prompts is indeed one exciting extension of our work, but I haven't yet shown it can be done. (There's some related work in this area, eg https://arxiv.org/abs/2305.14788)
