### ISSUE TITLE
look me!

### ISSUE THREAD

**Issue by Tshor** [jayelm/gisting#19]
https://github.com/jayelm/dialog-qa/blob/master/run_bert.sh 
Could you provide more context or clarify the request? Are you asking about how the file "coqa-train-v1.0-processed-bert-uncased.json" was generated and if there's any archived information about it? I'd appreciate further details to assist you better!

**Comment by jayelm** [comment]
Hi - I'm not sure I understand entirely what you're asking here, but please open an issue on the dialog-qa repository for help there. Though note that that repository is very old and it was never an official "release", just a scratch workspace for myself, so I can't guarantee that I'll be able to help.
