### ISSUE TITLE
Could you provide more training details?

### ISSUE THREAD

**Issue by aopolin-lv** [jayelm/gisting#2]
Could you provide more training details? For example, the requirement of CUDA memory during training.

**Comment by jayelm** [comment]
The README mentions that the large model runs (LLaMA-7B, FLAN-T5-XXL) expect

> 4 A100 80GB GPUs and at least 400GB of CPU RAM.

I adjusted the batch sizes to mostly take up all of the VRAM on the GPUs—it's likely you can get away with less VRAM and/or fewer GPUs by reducing the batch size but I haven't tested this extensively.

If you don't have GPU capacity an alternative is to train a smaller model, e.g. flan-t5-base or even flan-t5-small. The first command in the README should be doable on a GPU with only ~12GB VRAM.

Hope this helps!

**Comment by Aopolin-Lv** [comment]
> 

Thank you for your detailed reponse and suggestions.

**Comment by aopolin-lv** [comment]
> The README mentions that the large model runs (LLaMA-7B, FLAN-T5-XXL) expect
> 
> > 4 A100 80GB GPUs and at least 400GB of CPU RAM.
> 
> I adjusted the batch sizes to mostly take up all of the VRAM on the GPUs—it's likely you can get away with less VRAM and/or fewer GPUs by reducing the batch size but I haven't tested this extensively.
> 
> If you don't have GPU capacity an alternative is to train a smaller model, e.g. flan-t5-base or even flan-t5-small. The first command in the README should be doable on a GPU with only ~12GB VRAM.
> 
> Hope this helps!

Thank you for your detailed response and suggestions
